# Generated by Django 5.0.6 on 2024-07-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_initial_additional_info_client_initial_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='initial_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
