# Generated by Django 5.0.6 on 2024-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='remaining_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
