# Generated by Django 5.0.6 on 2024-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_currency_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='currency_type',
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=3),
        ),
    ]
